### ISSUE TITLE
postgis插件安装失败

### ISSUE THREAD

**Issue by cbdb-jixp** [cbdb-project/cbdb-online-query-app#48]
![mmexport1731413431579](https://github.com/user-attachments/assets/35fb415d-f4c9-459f-a2b8-b2e587c736d9)
centos7主机安装postgis插件报错，cbdb通过源码方式编译安装，版本1.6.0-302406171，postgis2.5.0通过rpm包方式安装。报错信息:[gpadmin@cbdb-coordinator ~]$ psql postgres psql (14.4， server 14.4) Type "help" for help.
postgres=# CREATE EXTENSION postgis;
ERROR: could not access file "$libdir/postgis-2.0": No such file or directory postgres=# CREATE EXTENSION address_standardizer;
ERROR: could not access file "$libdir/address_standardizer-3": No such file or directory postgres=

**Comment by cbdb-jixp** [comment]
请问这个$libdir默认是哪个路径？如何自定义设置？

**Comment by nicky258irl** [comment]
你好，网页版（这个项目）没有用到 postgis 插件哦

**Comment by nicky258irl** [comment]
我猜是不是 $libdir 这个变量没有设置？
